import type { Metadata } from "next";
import { Commissioner } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Commissioner({ subsets: [] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[var(--blue-medium)]`}>
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
